# Análisis Exploratorio de Datos (EDA)

In [ ]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
import seaborn as sns

sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

In [5]:
df_train = pd.read_csv('../data/splits/train.csv')
df_train.head()
#df_train.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,City Hotel,0,76,2015,September,38,16,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,13.0,NaN,0,Transient,71.4,0,1,Check-Out,2015-09-23
1,City Hotel,0,64,2016,May,21,17,0,2,1,0.0,0,BB,RUS,Corporate,TA/TO,0,0,0,A,B,0,No Deposit,NaN,218.0,0,Transient-Party,130.0,0,0,Check-Out,2016-05-19
2,Resort Hotel,0,9,2016,April,18,28,0,1,1,0.0,0,BB,NaN,Corporate,Corporate,0,0,0,A,A,0,No Deposit,NaN,94.0,0,Transient-Party,39.0,0,0,Check-Out,2016-04-29
3,City Hotel,0,44,2016,June,25,18,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,A,0,No Deposit,6.0,NaN,0,Transient,96.3,0,0,Check-Out,2016-06-20
4,Resort Hotel,1,21,2017,April,17,29,1,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,NaN,0,Transient,125.0,0,2,Canceled,2017-04-16

In [7]:
print(f"Dimensiones del dataset de entrenamiento: {df_train.shape}")   # (registros, variables)
df_train.info(memory_usage="deep")
resumen = pd.DataFrame({
    "tipo": df_train.dtypes,
    "n_unicos": df_train.nunique(),
    "n_faltantes": df_train.isna().sum(),
    "%_faltantes": (df_train.isna().mean() * 100).round(2),
})
resumen

Dimensiones del dataset de entrenamiento: (61177, 32)
<class 'pandas.DataFrame'>
RangeIndex: 61177 entries, 0 to 61176
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           61177 non-null  str
 1   is_canceled                     61177 non-null  int64
 2   lead_time                       61177 non-null  int64
 3   arrival_date_year               61177 non-null  int64
 4   arrival_date_month              61177 non-null  str
 5   arrival_date_week_number        61177 non-null  int64
 6   arrival_date_day_of_month       61177 non-null  int64
 7   stays_in_weekend_nights         61177 non-null  int64
 8   stays_in_week_nights            61177 non-null  int64
 9   adults                          61177 non-null  int64
 10  children                        61173 non-null  float64
 11  babies                          61177 non-null  int64
 12  meal                            61177 non-null  str
 13  country                         60856 non-null  str
 14  market_segment                  61177 non-null  str
 15  distribution_channel            61177 non-null  str
 16  is_repeated_guest               61177 non-null  int64
 17  previous_cancellations          61177 non-null  int64
 18  previous_bookings_not_canceled  61177 non-null  int64
 19  reserved_room_type              61177 non-null  str
 20  assigned_room_type              61177 non-null  str
 21  booking_changes                 61177 non-null  int64
 22  deposit_type                    61177 non-null  str
 23  agent                           52625 non-null  float64
 24  company                         3717 non-null   float64
 25  days_in_waiting_list            61177 non-null  int64
 26  customer_type                   61177 non-null  str
 27  adr                             61177 non-null  float64
 28  required_car_parking_spaces     61177 non-null  int64
 29  total_of_special_requests       61177 non-null  int64
 30  reservation_status              61177 non-null  str
 31  reservation_status_date         61177 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 48.1 MB

                                   tipo  n_unicos  n_faltantes  %_faltantes
hotel                               str         2            0         0.00
is_canceled                       int64         2            0         0.00
lead_time                         int64       467            0         0.00
arrival_date_year                 int64         3            0         0.00
arrival_date_month                  str        12            0         0.00
arrival_date_week_number          int64        53            0         0.00
arrival_date_day_of_month         int64        31            0         0.00
stays_in_weekend_nights           int64        16            0         0.00
stays_in_week_nights              int64        33            0         0.00
adults                            int64        11            0         0.00
children                        float64         5            4         0.01
babies                            int64         5            0         0.00
meal                                str         5            0         0.00
country                             str       166          321         0.52
market_segment                      str         8            0         0.00
distribution_channel                str         5            0         0.00
is_repeated_guest                 int64         2            0         0.00
previous_cancellations            int64        13            0         0.00
previous_bookings_not_canceled    int64        62            0         0.00
reserved_room_type                  str        10            0         0.00
assigned_room_type                  str        11            0         0.00
booking_changes                   int64        19            0         0.00
deposit_type                        str         3            0         0.00
agent                           float64       317         8552        13.98
company                         float64       305        57460        93.92
days_in_waiting_list              int64       119            0         0.00
customer_type                       str         4            0         0.00
adr                             float64      7354            0         0.00
required_car_parking_spaces       int64         5            0         0.00
total_of_special_requests         int64         6            0         0.00
reservation_status                  str         3            0         0.00
reservation_status_date             str       917            0         0.00